site_name: mkdocs-drawio-exporter example
plugins:
  - search
  - glightbox
  - drawio-exporter:
      format: svg
      drawio_args: [--no-sandbox, --disable-gpu]

nav:
  - Index: index.md
  - My page: my-page.md
  - My folder index: my-folder/index.md
  - My folder my page: my-folder/my-page.md
