name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Counterintuitively, we need to install Poetry before Python, because we source the Python
      # version from pyproject.toml. The runner's default version of Python should be okay here.
      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: poetry
          python-version: "${{ matrix.python }}"

      - name: Install dependencies
        run: poetry install --with dev

      - name: Publish
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
          poetry publish --build
